### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Qwaxy** [SkinnyDevi/scriptable#1]
currentAnime.json does not exist. Use fileExists(filePath) on a FileManager to check if a file exists.

Error on line 405:20: TypeError: null is not an object (evaluating 'animeFromJSON.title')

**Comment by SkinnyDevi** [comment]
Hey there, thanks for the feedback. Do you mind sharing what steps you took to reproduce the problem? And very sorry for the late response.

If you have not got the error again, please share what you did to fix it and close the issue. Many thanks!

**Comment by SkinnyDevi** [comment]
Hey there, thanks for the feedback. Do you mind sharing what steps you took to reproduce the problem? And very sorry for the late response.

If you have not got the error again, please share what you did to fix it and close the issue. Many thanks!
